name : commands

on: [push]

jobs:
  run-shell-commands:
    runs-on: ubuntu-22.04
    steps:
      - name : echo a string
        run: echo "hello a world"
      - name : multiline
        run: |
          node -v
          npm -v
